= CyberSecurity Considerations for Blockchain
Doc Writer <smsharif@secunoid.com>
v0.1, 14th October, 2019
:numbered:
:sectnum:
:sectnumlevels: 5
:chapter-label:
:toc: right
:toclevels: 5
:docinfo:
:docinfo1:
:docinfo2:
:description: This document covers all aspects of cybersecurity as related to blockchain technology
:keywords: cybersecurity, it security, blockchain
:imagesdir: images
:stylesheet:
:homepage: https://www.securityprivacyrisk.com
'''

<<<
== Overview
Relational databases were first introduced in 1970’s, prior to that, databases existed in one form or the other.  When relational databases became mainstream, their availability became a concern, and as a result various database vendors provided data replication capabilities amongst the databases.

Distributed ledgers are pretty much repositories that rely on a consensus algorithm to replicate data across geographically disparate ledgers. 
Blockchain is one of the implementations of distributed ledger technology.
Bitcoin was the very first use case of the distributed ledger technology using a specific consensus algorithm, proof of work.   

Since the inception of Bitcoin, which is also cryptocurrency, various other implementations of cryptocurrencies came into existence and are called Alternate Coins or Alt Coins, some examples are:

. Litecoin
. Darkcoin
. Dogecoin
. IOTA

After the cryptocurrency craze, the business users started thinking of other use cases such as the need to implement some form of logic into blockchain, this would allow decisions based on parameters. As a result, Ethereum introduced this ability to implement logic as smart contracts. Then after Ethereum other implementations came to light which were private or public.  This stack allowed users the ability to implement Distributed Applications  (Dapp) on the distributed ledger.  Some of the implementations that seem to improve on Ethereum are:

. Steem
. EOS
. Peerplays
. Hyperledger
. Tezos

While the industry dabbles with various technologies, and implementation of smart contracts , the key to implementation would be the security of the underlying platform.

<<<
== Goals
This paper will present security framework that can be leveraged for private/public blockchain implementations of the Distributed Ledger technology. Some of the areas to consider are:

. Security Organization
. Privacy & Data Protection
. Security Policy
. Security Manual
. Security Standards
. Security Guidelines
. Security Architecture
. Security Operations
. Governance, Risk, & Compliance

<<<
== Blockchain
Blockchain is an implementation of a DL,  and in my opinion, the key ingredients are:

. Users: Entities generating transactions when they send/receive bitcoin.
. Distributed Ledger: All transactions are written all active nodes participating in the network.  It should rather be called 
. Malleability:  Transactions written to the Blockchain cannot be changed as everyone has the same copy, no one party can change a transaction on their own, unless they own 51% of the hashing power. 
. Proof of Work: To generate a block, the miners are given a range, within which the hash of their block should be in, if the hash is within the range, the miner gets a reward, which is a Bitcoin.  This activity of finding the hash value within a certain range is very resource intensive and requires multiple miners working together to solve this problem. Once this block is generated, the miner announces it to the network of nodes running the distributed ledgers that the problem has been solved and they can move to solving another block.  Proof of work algorithm addresses the issues with multiple miners announcing that they have solved the problem.
. Miners: Entities with distributed ledgers who are using their computers to package x number of transactions into blocks. 

=== Blockchain Platforms
Some blockchain implementations include 1,2, and 3, but depending on what the consensus algorithm has implemented as in 4 above, 5 may or may not even exist.
As more features get added to the DL platforms, they become more complex, and so does the security.

For instance Ethereum uses a scripting engine to translate smart contracts written in Solidity, Ethereum Virtual Machine has been developed by a group of developers but a thorough code review has not be done on it.

<<<
== Deployment Models
This section will outline the models in use and their impacts to user privacy.

=== Centralized
All web platforms in use today are deployed using the centralized model.  For instance, _Facebook_ has all user data in their data centres.  Users have to login to _Facebook_ servers to establish communications with other users. Centralization introduces following risks:

* Mis-use
* Honeypot, where there is so much data in one location, it becomes a target for hackers.
* Censorship
* Monitoring

Classic examples would be the difference between you using fiat vs electronic means such as:

* Credit card
* Debit card
* Electronic Funds Transfer(EFT)

When spending fiat, following table summarizes privacy impacts. (Traceability diminishing as you go down the list):

[frame=topbot]
[Caption: Table 1]
.Transaction Traceability
[%autowidth]
,===
No,Source, Spend Method, Traceability

1,Any,Electronic, High
2,Bank,Fiat,Medium
3,Employer,Fiat,Medium 
4,Family/Friend,Fiat, Low
,===

No matter what the source of income is, if you spend it via:

* Electronic means, all your transactions are highly traceable. An individual has no privacy at all.
* Non electronic means, only the party providing the funds knows who they provided the funds to, where it was spent they have no idea. An individuals privacy is well protected.

=== De-centralized
In a decentralized model, there is no cental body, users interact with each other via direct connections.  No central entity is able to control their actions or data

=== Hybrid

<<<
== Consensus Protocols
Following are the predominant consensus protocols that are use by the distributed ledger implementations.

.. *Proof of Work* uses computational power to validate new blocks of data.  To participate in this scheme, participants are required to collate transactions within a single block and then apply a hash function with the use of some additional metadata.  Proof of Stake	Validators (special nodes) voting on valid blocks whilst posting collateral in order to be able to participate in the validation process. 

.. *Proof of Stake* relies on proving the user is invested in the underlying token of value of the network being mined rather than being the owner of a large amount of computing power

.. *Ripple Protocol* In order to validate new transactions, servers amalgamate outstanding transactions into a “candidate list.” All participants then vote on valid transactions to be included in the ledger.  Transactions that meet the 80% threshold of “yes” votes are included within the following last closed ledger state.

.. *Proof of Elapsed Time*	As part of its Intelledger proposal, Intel has devised a means of establishing a validation lottery that takes advantage of the capability of its CPUs to produce a timestamp cryptographically signed by the hardware. Whoever in the chain has the next soonest timestamp will be the one to decide which transactions will be a part of the next block in the chain. 
This consensus method is extremely energy efficient compared to Proof of Work and therefore more adapted to IoT devices.

<<<
== Adhoc Notes
* Network (and cloud) security has changed signifivantly
** Our network protection controls have to advance and improve to keep up with attacks
* An additional level of application controls is needed that includes:
** Trust analysis and realtionships
** Application behaviour anlysis
** Dynamic policy for prevention/detection

*Micro-segmentation* is a model of defining network isolation polcies that alllows oranizaiont sto segment and control workloads based on applicaiton provilres and workload attributes
** The focus is on making network security more granular and controllable
** also a shift toward internal network focus, versus "the perimieter"
** Each asset has a permeter, and a software-defined perimeter policy that is attached to it and evaluated during interactions with other systems

<<<
== Terms Used

* ATT&CK - Adversatial Tactics Techniques & Common Knowledge
* IOC - Indicators of Compromise
* OSINT - Open Source Inteligence Tools
* TTP - Techniques, Tactics, Procedures

<<<
[bibliography]
== References
. Writing Position Papers: http://www.studygs.net/wrtstr9.htm 
. Cover Page graphic: https://www.pinterest.com/pin/352758583290504850/ 



