= Information Security Patterns
Doc Writer <ssharif@secunoid.com>
v1.22.04.10.01
:numbered:
:sectnum:
:sectnumlevels: 5
:chapter-label:
:toc: right
:toclevels: 5
:docinfo:
:docinfo1:
:docinfo2:
:description: This document lists patterns for various problems in information security
:keywords: information security, cyber security, it security, data security, compliance, risk management, patterns, solutions
:imagesdir: images
:stylesheet:
:homepage: https://www.secunoid.com
'''
== Layered Security

=== Alias

* Tiered/Distributed Security
* Defense in Depth
* Belt and Suspenders

=== Motivation
Networked applications are susceptible to many forms of attack that may target the network, host or application layer and the communication between them. Naturally, the overall security of a system is greatly improved when each one of these layers are identified, protected, and audited for possible weakness.

Moreover, attacks may originate internally or externally. Basing security rules on the premise of internal users are good and external users are bad is fundamentally flawed (read insider threat) and difficult to manage. With increased use of external business communication channels, it therefore becomes much more difficult to identify which users or sessions are internal and which are external.

=== Problem
Networked applications and the environment within which they operate are vulnerable at many layers and from all directions. Each device, data object, session, file and process is a potential target and needs to be identified and secured.

=== Forces
* Once standalone applications are suddenly now networked and unprepared to withstand network attacks.
* Protection of any one of network, server or application is not sufficient to adequately protect the data within an enterprise.
* While one or many components of a system may be protected, it truly is only as secure as the weakest link.
* If a single devices or application fails or is misconfigured it could potentially expose all private resources.

=== Solution
Employ security measures at all layers of a networked application and throughout its operating environment.

Router ACLs, address translation and intrusion detection systems protect the network layer. OS hardening, thoughtful application installation and configuration protect the host and the applications that run on it. Practicing secure coding techniques protect all of the above. Finally, proper baselining and monitoring methodologies protect all these layers on an ongoing basis.

Don't ignore insider threat. Intrusions and attacks can originate from the inside just as they can from the outside. Authentication, authorization, antivirus software, and intrusion detection systems should protect resources from both sides of the corporate boundary.

=== Example
* Firewalls provide ingress/egress packet and protocol filtering.
* Application servers and 3rd party services authenticate users over SSL.
* Applications validate form data by length, bounds and type.
* All network and application activity is monitored and logged for analysis.

=== Consequences
* [*] Greatly improved overall security
* [*] Reduced exposure to attack if one security measure should be subverted or misconfigured
* [*] Continuously validates security efforts
* [ ] More complex security architecture

=== Related Patterns
Risk Assessment and Management

== Pattern Template
*Pattern Name (Scope, Purpose)*
The pattern's name conveys the essence of the pattern succinctly. A good name is vital, because it will become part of your design vocabulary.

*Intent*
A short statement that answers the following questions: What does the design pattern do? What is its rationale and intent? What particular design issue or problem does it address?

*Also Known As*
Other well-known names for the pattern, if any.

*Motivation*
A scenario that illustrates a design problem and how the class and object structures in the pattern solve the problem. The scenario will help you understand the more abstract description of the pattern that follows.

*Applicability*
What are the situations in which the design pattern can be applied? What are examples of poor designs that the pattern can address? How can you recognize these situations?
An applicable situation

*Structure*

*Participants*
The classes and/or objects participating in the design pattern and their responsibilities.

*Participant Name*
Responsibility for what

*Collaborations*
How the participants collaborate to carry out their responsibilities.

. [Collaboration]

*Consequences*
How does the pattern support its objectives? What are the trade-offs and results of using the pattern? What aspect of system structure does it let you vary independently?
A consequence bullet. Description of consequence

*Implementation*
What pitfalls, hints, or techniques should you be aware of when implementing the pattern? Are there language-specific issues?
An implementation Bullet. Description of Bullet

*Sample Code and Usage*
Code fragments that illustrate how you might implement the pattern in C++ or Smalltalk.
Program Listing

*Known Uses*
Examples of the pattern found in real systems. We include at least two examples from different domains.

*Related Patterns*
What design patterns are closely related to this one? What are the important differences? With which other patterns should this one be used?